name: flutter_launcher_name
description: A command-line tool which simplifies the task of updating your Flutter app's launcher name.
version: 0.0.2
homepage: https://github.com/the-coding-turtle/flutter_launcher_name

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter